# Generated by Django 4.0.4 on 2022-05-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('entrance_data', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(choices=[('PC', 'Штук'), ('KG', 'Килограм')], default='PC', max_length=2)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.supplier')),
            ],
        ),
    ]
