# Generated by Django 4.0.4 on 2022-06-03 08:38

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('productsapp', '0002_productcategory_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='products',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='products',
            name='site',
            field=models.ManyToManyField(null=True, to='sites.site'),
        ),
    ]
