# Generated by Django 4.0.4 on 2022-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('productsapp', '0003_alter_productcategory_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='site',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
